#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | grep '\.php$')
[ -z "$FILES" ] && exit 0

# Fix known issues
echo "$FILES" | xargs ./vendor/bin/phpcbf

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
